using PresentationManager.Domain.Enums;

namespace PresentationManager.Domain.Entities;

/// <summary>A desktop login account — only Operator/Admin/SuperAdmin ever authenticate this way.</summary>
public class User
{
    public int Id { get; set; }

    public required string Username { get; set; }

    /// <summary>Packed "iterations.saltBase64.hashBase64" — see <c>PasswordHasher</c>.</summary>
    public required string PasswordHash { get; set; }

    public required string FullName { get; set; }

    public UserRole Role { get; set; }

    public bool IsActive { get; set; } = true;

    /// <summary>Set once this Admin links their desktop login to a Telegram chat (via a one-time code
    /// generated by <c>AdminPanelForm</c>'s "Botga ulash" button and consumed by the bot's <c>/start</c> deep
    /// link) - lets the Telegram bot show them their own projects/participants/scores and do basic project
    /// management, mirroring the Admin panel. Null for accounts that never linked, and for Operator/SuperAdmin
    /// accounts, which have no bot-side counterpart today.</summary>
    public long? TelegramChatId { get; set; }

    /// <summary>Captured alongside <see cref="TelegramChatId"/> at link time - lets the "Parolni unutdingizmi?"
    /// flow (<c>ForgotPasswordForm</c>) look this account up by Telegram @username rather than by
    /// <see cref="TelegramChatId"/>, which the person resetting their password has no direct way to know.</summary>
    public string? TelegramUsername { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
